services:
  panoptikauth:
    image: docker.io/billos/panoptikauth:2.4.0
    container_name: panoptikauth
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: panoptikauth-redis
    restart: unless-stopped
